name: Add a new TF variable
description: Will trigger an update to the `issue.tfvars.json` file.
title: "[TFVARS]: "
labels: ["tfvars"]

# more input types here in GH Docs
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#about-yaml-syntax-for-issue-forms
body:
  - type: input
    id: sample_input1
    attributes:
      label: Value to set in tfvars.json
    validations:
      required: true
