name: Run Terraform apply on PR merge to main

on:
  pull_request:
    types:
      - closed
    branches:
      - main # merges have the ref of the merged-into branch

concurrency: main

jobs:
  apply:
    uses: ./.github/workflows/terraform-apply.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      tf_root_dir: "./"
      tf_version: "1.2.3"
      pr_number: ${{ github.event.pull_request.number }}
