name: Run Terraform plan on PR open

on: 
  pull_request:

concurrency: main

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      tf_root_dir: "./"
      tf_version: "1.2.3"
      pr_number: ${{ github.event.pull_request.number }}

